export const EDS_ERR_OK = 0;

export const EDS_PROPERTY_EVENT_ALL = 0x100;
export const EDS_OBJECT_EVENT_ALL = 0x200;
export const EDS_STATE_EVENT_ALL = 0x300;

export const EDS_OBJECT_EVENT_DIR_ITEM_REQUEST_TRANSFER = 0x208;

export const EDS_PROP_ID_SAVE_TO = 0xb;
export const EDS_SAVE_TO_HOST = 2;

export const EDS_PROP_ID_DRIVE_MODE = 0x401;
export const EDS_DRIVE_MODE_CONTINUOUS = 0x1;

export const EDS_FILE_CREATE_DISPOSITION_CREATE_ALWAYS = 1;
export const EDS_ACCESS_WRITE = 1;

export const EDS_CAMERA_COMMAND_TAKE_PICTURE = 0x0;

export const EDS_CAMERA_COMMAND_PRESS_SHUTTER_BUTTON = 0x4;
export const EDS_CAMERA_COMMAND_SHUTTER_BUTTON_OFF = 0x0;
export const EDS_CAMERA_COMMAND_SHUTTER_BUTTON_HALFWAY = 0x1;
export const EDS_CAMERA_COMMAND_SHUTTER_BUTTON_COMPLETELY = 0x3;
